### ISSUE TITLE
Checklist Tutorial 3 and 4

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/scc#131]
Add and /or update the checklist for Tutorial 3 and 4

- Each list on the item should correspond with the different sections that they have to cover ( see Tut 1 or 2 as an example)

**Comment by sfebruary** [comment]
@mmhashatsi I can't see anything that needs to be updated in Tutorial 4 (the section that deals with Monitoring). Please elaborate in case I'm missing something.

**Comment by mmhashatsi** [comment]
@sfebruary the checklist on Tut 3 and Tut 4 at the moment only contain some of the sections, not all the sections that are covered in that tutorial, please add the other sections as well

**Comment by nyameko** [comment]
Tut 3 is done, I'll attend to tut 4 tomorrow.
